// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjNwgvsyS-hkyCGGbSMAS80tm3Qb9-hYo',
    appId: '1:367086669000:web:cdb6c7935bfa3569c129fd',
    messagingSenderId: '367086669000',
    projectId: 'fir-riverpod-d50be',
    authDomain: 'fir-riverpod-d50be.firebaseapp.com',
    storageBucket: 'fir-riverpod-d50be.firebasestorage.app',
    measurementId: 'G-1V9ZGNQCRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKYf5lVWJWZ7XATmS5QgyIThrevDvdN3Q',
    appId: '1:367086669000:android:44191cf85b02834ac129fd',
    messagingSenderId: '367086669000',
    projectId: 'fir-riverpod-d50be',
    storageBucket: 'fir-riverpod-d50be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ImR1csAcqSOFS22U3RjR5jp42WtHCOM',
    appId: '1:367086669000:ios:4f345aea5b08b34bc129fd',
    messagingSenderId: '367086669000',
    projectId: 'fir-riverpod-d50be',
    storageBucket: 'fir-riverpod-d50be.firebasestorage.app',
    iosBundleId: 'com.example.testProjectAthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ImR1csAcqSOFS22U3RjR5jp42WtHCOM',
    appId: '1:367086669000:ios:4f345aea5b08b34bc129fd',
    messagingSenderId: '367086669000',
    projectId: 'fir-riverpod-d50be',
    storageBucket: 'fir-riverpod-d50be.firebasestorage.app',
    iosBundleId: 'com.example.testProjectAthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjNwgvsyS-hkyCGGbSMAS80tm3Qb9-hYo',
    appId: '1:367086669000:web:5c701b3c783d09bdc129fd',
    messagingSenderId: '367086669000',
    projectId: 'fir-riverpod-d50be',
    authDomain: 'fir-riverpod-d50be.firebaseapp.com',
    storageBucket: 'fir-riverpod-d50be.firebasestorage.app',
    measurementId: 'G-P4P0K18KVT',
  );
}
